//Sign In User
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING';
export const LOGIN_USER_REJECTED = 'LOGIN_USER_REJECTED';
export const LOGIN_USER_FULFILLED = 'LOGIN_USER_FULFILLED';