//Sign In User
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING';
export const LOGIN_USER_REJECTED = 'LOGIN_USER_REJECTED';
export const LOGIN_USER_FULFILLED = 'LOGIN_USER_FULFILLED';

export const FETCH_ENTRIES = 'FETCH_ENTRIES';
export const FETCH_ENTRIES_PENDING = 'FETCH_ENTRIES_PENDING';
export const FETCH_ENTRIES_FULFILLED = 'FETCH_ENTRIES_FULFILLED';
export const FETCH_ENTRIES_REJECTED = 'FETCH_ENTRIES_REJECTED';

export const ADD_ENTRY = 'ADD_ENTRY';
export const ADD_ENTRY_PENDING = 'ADD_ENTRY_PENDING';
export const ADD_ENTRY_FULFILLED = 'ADD_ENTRY_FULFILLED';
export const ADD_ENTRY_REJECTED = 'ADD_ENTRY_REJECTED';

export const ADD_ENTRY_TO_SERVER = 'ADD_ENTRY_TO_SERVER';
export const ADD_ENTRY_TO_SERVER_PENDING = 'ADD_ENTRY_TO_SERVER_PENDING';
export const ADD_ENTRY_TO_SERVER_FULLFILED = 'ADD_ENTRY_TO_SERVER_FULLFILED';
export const ADD_ENTRY_TO_SERVER_REJECTED = 'ADD_ENTRY_TO_SERVER_REJECTED';

export const SHOW_SLEEPING_QUALITY = 'SHOW_SLEEPING_QUALITY';
export const SHOW_TIREDNESS_FEELING = 'SHOW_TIREDNESS_FEELING';
export const SET_CALENDAR_VIEW = 'SET_CALENDAR_VIEW';
